// flow-typed signature: 8b3d419287c0930ce35b5fb29f72ff04
// flow-typed version: <<STUB>>/bitcoin-core_vgit://github.com/Greg-Griffith/bitcoin-core.git/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bitcoin-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bitcoin-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bitcoin-core/dist/src/errors/rpc-error' {
  declare module.exports: any;
}

declare module 'bitcoin-core/dist/src/errors/standard-error' {
  declare module.exports: any;
}

declare module 'bitcoin-core/dist/src/index' {
  declare module.exports: any;
}

declare module 'bitcoin-core/dist/src/logging/request-logger' {
  declare module.exports: any;
}

declare module 'bitcoin-core/dist/src/logging/request-obfuscator' {
  declare module.exports: any;
}

declare module 'bitcoin-core/dist/src/methods' {
  declare module.exports: any;
}

declare module 'bitcoin-core/dist/src/parser' {
  declare module.exports: any;
}

declare module 'bitcoin-core/dist/src/requester' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bitcoin-core/dist/src/errors/rpc-error.js' {
  declare module.exports: $Exports<'bitcoin-core/dist/src/errors/rpc-error'>;
}
declare module 'bitcoin-core/dist/src/errors/standard-error.js' {
  declare module.exports: $Exports<'bitcoin-core/dist/src/errors/standard-error'>;
}
declare module 'bitcoin-core/dist/src/index.js' {
  declare module.exports: $Exports<'bitcoin-core/dist/src/index'>;
}
declare module 'bitcoin-core/dist/src/logging/request-logger.js' {
  declare module.exports: $Exports<'bitcoin-core/dist/src/logging/request-logger'>;
}
declare module 'bitcoin-core/dist/src/logging/request-obfuscator.js' {
  declare module.exports: $Exports<'bitcoin-core/dist/src/logging/request-obfuscator'>;
}
declare module 'bitcoin-core/dist/src/methods.js' {
  declare module.exports: $Exports<'bitcoin-core/dist/src/methods'>;
}
declare module 'bitcoin-core/dist/src/parser.js' {
  declare module.exports: $Exports<'bitcoin-core/dist/src/parser'>;
}
declare module 'bitcoin-core/dist/src/requester.js' {
  declare module.exports: $Exports<'bitcoin-core/dist/src/requester'>;
}
