// flow-typed signature: e7a71a53ca2cc1ff018bee523f8a3517
// flow-typed version: <<STUB>>/bootstrap-material-design_v^0.5.10/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-material-design'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-material-design' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap-sprockets' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/affix' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/alert' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/button' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/carousel' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/collapse' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/dropdown' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/modal' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/popover' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/scrollspy' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/tab' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/tooltip' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/transition' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/dist/js/bootstrap' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/dist/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/dist/js/npm' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/grunt/bs-commonjs-generator' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/grunt/bs-glyphicons-data-generator' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/grunt/bs-lessdoc-parser' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/grunt/bs-raw-files-generator' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/Gruntfile' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/js/affix' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/js/alert' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/js/button' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/js/carousel' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/js/collapse' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/js/dropdown' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/js/modal' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/js/popover' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/js/scrollspy' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/js/tab' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/js/tooltip' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/bootstrap/js/transition' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/dist/jquery' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/dist/jquery.min' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/dist/jquery.slim' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/dist/jquery.slim.min' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/ajax' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/jsonp' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/load' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/parseJSON' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/parseXML' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/script' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/var/location' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/var/nonce' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/var/rquery' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/xhr' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/attributes' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/attributes/attr' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/attributes/classes' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/attributes/prop' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/attributes/support' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/attributes/val' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/callbacks' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/core' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/core/access' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/core/DOMEval' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/core/init' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/core/parseHTML' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/core/ready' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/core/support' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/core/var/rsingleTag' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/css' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/css/addGetHookIf' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/css/adjustCSS' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/css/curCSS' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/css/defaultDisplay' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/css/hiddenVisibleSelectors' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/css/showHide' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/css/support' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/css/var/cssExpand' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/css/var/getStyles' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/css/var/isHidden' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/css/var/rmargin' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/css/var/rnumnonpx' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/css/var/swap' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/data' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/data/accepts' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/data/Data' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/data/support' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/data/var/acceptData' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/data/var/dataPriv' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/data/var/dataUser' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/deferred' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/deferred/exceptionHook' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/deprecated' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/dimensions' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/effects' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/effects/animatedSelector' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/effects/support' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/effects/Tween' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/event' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/event/ajax' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/event/alias' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/event/focusin' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/event/support' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/event/trigger' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/exports/amd' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/exports/global' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/intro' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/jquery' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/_evalUrl' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/buildFragment' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/createSafeFragment' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/getAll' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/setGlobalEval' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/support' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/var/nodeNames' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/var/rcheckableType' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/var/rleadingWhitespace' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/var/rscriptType' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/var/rtagName' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/wrapMap' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/offset' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/outro' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/queue' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/queue/delay' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/selector-native' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/selector-sizzle' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/selector' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/serialize' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/support' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/traversing' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/traversing/findFilter' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/traversing/var/dir' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/traversing/var/rneedsContext' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/traversing/var/siblings' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/var/arr' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/var/class2type' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/var/concat' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/var/deletedIds' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/var/document' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/var/documentElement' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/var/hasOwn' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/var/indexOf' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/var/pnum' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/var/push' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/var/rcssNum' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/var/rnotwhite' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/var/slice' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/var/support' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/var/toString' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/bower_components/jquery/src/wrap' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/dist/js/material' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/dist/js/material.min' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/dist/js/ripples' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/dist/js/ripples.min' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/scripts/index' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/scripts/material' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/scripts/ripples' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/test/materialSpec' {
  declare module.exports: any;
}

declare module 'bootstrap-material-design/test/ripplesSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap-sprockets.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap-sprockets'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap.min'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/affix.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/affix'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/alert.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/alert'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/button.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/button'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/carousel.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/carousel'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/collapse.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/collapse'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/dropdown.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/dropdown'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/modal.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/modal'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/popover.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/popover'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/scrollspy.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/scrollspy'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/tab.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/tab'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/tooltip.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/tooltip'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/transition.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap-sass/assets/javascripts/bootstrap/transition'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/dist/js/bootstrap.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/dist/js/bootstrap'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/dist/js/bootstrap.min.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/dist/js/bootstrap.min'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/dist/js/npm.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/dist/js/npm'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/grunt/bs-commonjs-generator.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/grunt/bs-commonjs-generator'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/grunt/bs-glyphicons-data-generator.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/grunt/bs-glyphicons-data-generator'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/grunt/bs-lessdoc-parser.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/grunt/bs-lessdoc-parser'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/grunt/bs-raw-files-generator.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/grunt/bs-raw-files-generator'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/Gruntfile.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/Gruntfile'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/js/affix.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/js/affix'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/js/alert.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/js/alert'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/js/button.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/js/button'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/js/carousel.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/js/carousel'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/js/collapse.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/js/collapse'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/js/dropdown.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/js/dropdown'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/js/modal.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/js/modal'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/js/popover.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/js/popover'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/js/scrollspy.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/js/scrollspy'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/js/tab.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/js/tab'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/js/tooltip.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/js/tooltip'>;
}
declare module 'bootstrap-material-design/bower_components/bootstrap/js/transition.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/bootstrap/js/transition'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/dist/jquery.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/dist/jquery'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/dist/jquery.min.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/dist/jquery.min'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/dist/jquery.slim.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/dist/jquery.slim'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/dist/jquery.slim.min.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/dist/jquery.slim.min'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/ajax.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/ajax'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/jsonp.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/ajax/jsonp'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/load.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/ajax/load'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/parseJSON.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/ajax/parseJSON'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/parseXML.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/ajax/parseXML'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/script.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/ajax/script'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/var/location.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/ajax/var/location'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/var/nonce.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/ajax/var/nonce'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/var/rquery.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/ajax/var/rquery'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/ajax/xhr.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/ajax/xhr'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/attributes.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/attributes'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/attributes/attr.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/attributes/attr'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/attributes/classes.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/attributes/classes'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/attributes/prop.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/attributes/prop'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/attributes/support.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/attributes/support'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/attributes/val.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/attributes/val'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/callbacks.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/callbacks'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/core.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/core'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/core/access.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/core/access'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/core/DOMEval.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/core/DOMEval'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/core/init.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/core/init'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/core/parseHTML.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/core/parseHTML'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/core/ready.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/core/ready'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/core/support.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/core/support'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/core/var/rsingleTag.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/core/var/rsingleTag'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/css.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/css'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/css/addGetHookIf.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/css/addGetHookIf'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/css/adjustCSS.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/css/adjustCSS'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/css/curCSS.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/css/curCSS'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/css/defaultDisplay.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/css/defaultDisplay'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/css/hiddenVisibleSelectors.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/css/hiddenVisibleSelectors'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/css/showHide.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/css/showHide'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/css/support.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/css/support'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/css/var/cssExpand.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/css/var/cssExpand'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/css/var/getStyles.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/css/var/getStyles'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/css/var/isHidden.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/css/var/isHidden'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/css/var/rmargin.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/css/var/rmargin'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/css/var/rnumnonpx.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/css/var/rnumnonpx'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/css/var/swap.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/css/var/swap'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/data.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/data'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/data/accepts.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/data/accepts'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/data/Data.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/data/Data'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/data/support.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/data/support'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/data/var/acceptData.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/data/var/acceptData'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/data/var/dataPriv.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/data/var/dataPriv'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/data/var/dataUser.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/data/var/dataUser'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/deferred.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/deferred'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/deferred/exceptionHook.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/deferred/exceptionHook'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/deprecated.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/deprecated'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/dimensions.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/dimensions'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/effects.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/effects'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/effects/animatedSelector.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/effects/animatedSelector'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/effects/support.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/effects/support'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/effects/Tween.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/effects/Tween'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/event.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/event'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/event/ajax.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/event/ajax'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/event/alias.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/event/alias'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/event/focusin.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/event/focusin'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/event/support.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/event/support'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/event/trigger.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/event/trigger'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/exports/amd.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/exports/amd'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/exports/global.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/exports/global'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/intro.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/intro'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/jquery.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/jquery'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/manipulation'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/_evalUrl.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/manipulation/_evalUrl'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/buildFragment.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/manipulation/buildFragment'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/createSafeFragment.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/manipulation/createSafeFragment'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/getAll.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/manipulation/getAll'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/setGlobalEval.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/manipulation/setGlobalEval'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/support.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/manipulation/support'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/var/nodeNames.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/manipulation/var/nodeNames'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/var/rcheckableType.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/manipulation/var/rcheckableType'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/var/rleadingWhitespace.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/manipulation/var/rleadingWhitespace'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/var/rscriptType.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/manipulation/var/rscriptType'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/var/rtagName.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/manipulation/var/rtagName'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/manipulation/wrapMap.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/manipulation/wrapMap'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/offset.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/offset'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/outro.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/outro'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/queue.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/queue'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/queue/delay.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/queue/delay'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/selector-native.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/selector-native'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/selector-sizzle.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/selector-sizzle'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/selector.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/selector'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/serialize.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/serialize'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/support.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/support'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/traversing.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/traversing'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/traversing/findFilter.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/traversing/findFilter'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/traversing/var/dir.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/traversing/var/dir'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/traversing/var/rneedsContext.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/traversing/var/rneedsContext'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/traversing/var/siblings.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/traversing/var/siblings'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/var/arr.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/var/arr'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/var/class2type.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/var/class2type'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/var/concat.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/var/concat'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/var/deletedIds.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/var/deletedIds'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/var/document.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/var/document'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/var/documentElement.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/var/documentElement'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/var/hasOwn.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/var/hasOwn'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/var/indexOf.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/var/indexOf'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/var/pnum.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/var/pnum'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/var/push.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/var/push'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/var/rcssNum.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/var/rcssNum'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/var/rnotwhite.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/var/rnotwhite'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/var/slice.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/var/slice'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/var/support.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/var/support'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/var/toString.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/var/toString'>;
}
declare module 'bootstrap-material-design/bower_components/jquery/src/wrap.js' {
  declare module.exports: $Exports<'bootstrap-material-design/bower_components/jquery/src/wrap'>;
}
declare module 'bootstrap-material-design/dist/js/material.js' {
  declare module.exports: $Exports<'bootstrap-material-design/dist/js/material'>;
}
declare module 'bootstrap-material-design/dist/js/material.min.js' {
  declare module.exports: $Exports<'bootstrap-material-design/dist/js/material.min'>;
}
declare module 'bootstrap-material-design/dist/js/ripples.js' {
  declare module.exports: $Exports<'bootstrap-material-design/dist/js/ripples'>;
}
declare module 'bootstrap-material-design/dist/js/ripples.min.js' {
  declare module.exports: $Exports<'bootstrap-material-design/dist/js/ripples.min'>;
}
declare module 'bootstrap-material-design/scripts/index.js' {
  declare module.exports: $Exports<'bootstrap-material-design/scripts/index'>;
}
declare module 'bootstrap-material-design/scripts/material.js' {
  declare module.exports: $Exports<'bootstrap-material-design/scripts/material'>;
}
declare module 'bootstrap-material-design/scripts/ripples.js' {
  declare module.exports: $Exports<'bootstrap-material-design/scripts/ripples'>;
}
declare module 'bootstrap-material-design/test/materialSpec.js' {
  declare module.exports: $Exports<'bootstrap-material-design/test/materialSpec'>;
}
declare module 'bootstrap-material-design/test/ripplesSpec.js' {
  declare module.exports: $Exports<'bootstrap-material-design/test/ripplesSpec'>;
}
