// flow-typed signature: 4f4c666a2984b36e09dee6f845093d20
// flow-typed version: <<STUB>>/child_process_v^1.0.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'child_process'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'child_process' {
  declare module.exports: any;
}
