// flow-typed signature: 61ba7bfa917c775c0646ed85fc8ba48e
// flow-typed version: <<STUB>>/electron-download-manager_vhttps://github.com/danmolitor/electron-download-manager.git/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-download-manager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-download-manager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-download-manager/index' {
  declare module.exports: $Exports<'electron-download-manager'>;
}
declare module 'electron-download-manager/index.js' {
  declare module.exports: $Exports<'electron-download-manager'>;
}
