// flow-typed signature: 617e43a51f25dc8a0de8af9714036644
// flow-typed version: <<STUB>>/lowdb_v^0.16.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lowdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lowdb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lowdb/dist/lowdb' {
  declare module.exports: any;
}

declare module 'lowdb/dist/lowdb.min' {
  declare module.exports: any;
}

declare module 'lowdb/lib/common' {
  declare module.exports: any;
}

declare module 'lowdb/lib/fp' {
  declare module.exports: any;
}

declare module 'lowdb/lib/main' {
  declare module.exports: any;
}

declare module 'lowdb/lib/nano' {
  declare module.exports: any;
}

declare module 'lowdb/lib/storages/_stringify' {
  declare module.exports: any;
}

declare module 'lowdb/lib/storages/browser' {
  declare module.exports: any;
}

declare module 'lowdb/lib/storages/file-async' {
  declare module.exports: any;
}

declare module 'lowdb/lib/storages/file-sync' {
  declare module.exports: any;
}

declare module 'lowdb/lib/storages/memory' {
  declare module.exports: any;
}

declare module 'lowdb/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lowdb/dist/lowdb.js' {
  declare module.exports: $Exports<'lowdb/dist/lowdb'>;
}
declare module 'lowdb/dist/lowdb.min.js' {
  declare module.exports: $Exports<'lowdb/dist/lowdb.min'>;
}
declare module 'lowdb/lib/common.js' {
  declare module.exports: $Exports<'lowdb/lib/common'>;
}
declare module 'lowdb/lib/fp.js' {
  declare module.exports: $Exports<'lowdb/lib/fp'>;
}
declare module 'lowdb/lib/main.js' {
  declare module.exports: $Exports<'lowdb/lib/main'>;
}
declare module 'lowdb/lib/nano.js' {
  declare module.exports: $Exports<'lowdb/lib/nano'>;
}
declare module 'lowdb/lib/storages/_stringify.js' {
  declare module.exports: $Exports<'lowdb/lib/storages/_stringify'>;
}
declare module 'lowdb/lib/storages/browser.js' {
  declare module.exports: $Exports<'lowdb/lib/storages/browser'>;
}
declare module 'lowdb/lib/storages/file-async.js' {
  declare module.exports: $Exports<'lowdb/lib/storages/file-async'>;
}
declare module 'lowdb/lib/storages/file-sync.js' {
  declare module.exports: $Exports<'lowdb/lib/storages/file-sync'>;
}
declare module 'lowdb/lib/storages/memory.js' {
  declare module.exports: $Exports<'lowdb/lib/storages/memory'>;
}
declare module 'lowdb/webpack.config.js' {
  declare module.exports: $Exports<'lowdb/webpack.config'>;
}
