// flow-typed signature: a99a039d9c8bcb49ee3b54073691af96
// flow-typed version: <<STUB>>/project-version_v^1.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'project-version'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'project-version' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'project-version/index' {
  declare module.exports: $Exports<'project-version'>;
}
declare module 'project-version/index.js' {
  declare module.exports: $Exports<'project-version'>;
}
