// flow-typed signature: 67b0674b80bd9e8392a22b655f24fe3f
// flow-typed version: <<STUB>>/ps-list_v^4.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ps-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ps-list' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ps-list/index' {
  declare module.exports: $Exports<'ps-list'>;
}
declare module 'ps-list/index.js' {
  declare module.exports: $Exports<'ps-list'>;
}
